### ISSUE TITLE
fivem white screen

### ISSUE THREAD

**Issue by gava12** [browlete/Fivem-Unban#1]
hello i run your fivem unban tool and now when i delete digital element to sign in an new acc i have problem fivem log in its white
![image](https://user-images.githubusercontent.com/104622389/221597635-d8b8a030-d2fa-4080-a983-87317753dccf.png)

**Comment by browlete** [comment]
Olá esse problema está relacionado ao launcher da rockstar. Você pode tentar reinstalar o launcher e o fivem para corrigir esse erro.
