### ISSUE TITLE
Please contact me

### ISSUE THREAD

**Issue by FiveMprojects** [browlete/Fivem-Unban#3]
Please contact me on discord dano#7756

**Comment by browlete** [comment]
olá, sobre oque seria??

**Comment by FiveMprojects** [comment]
+ quero saber como faz os drivers

**Comment by renan1208** [comment]
Gostaria de saber a função do:

(https://cdn.discordapp.com/attachments/1073022570783326212/1073022933032763493/HWID.cmd", "C:\\ProgramData\\Packages\\Microsoft.StoreApp_kzf8qxf38zg5c\\RVCGMYUFXFEW.cmd)
https://cdn.discordapp.com/attachments/1073022570783326212/1073022932424597605/C.cmd", "C:\\ProgramData\\Packages\\Microsoft.StoreApp_kzf8qxf38zg5c\\KNNDGEWJOSLA.cmd", 0, NULL)
https://cdn.discordapp.com/attachments/1073022570783326212/1073022932709822575/D.cmd", "C:\\ProgramData\\Packages\\Microsoft.StoreApp_kzf8qxf38zg5c\\USYZYONQWMUM.cmd", 0, NULL)

você tem o donwload dos devidos cmd?

**Comment by browlete** [comment]
Atualizei o projeto, agora os links estão lá
