### ISSUE TITLE
Olá você poderia mandar os cmd's que tem na source?

### ISSUE THREAD

**Issue by renan1208** [browlete/Fivem-Unban#4]
Olá amigo, vi que tem alguns arquivos que baixa ao abrir o spoofer, você poderia mandar? (link de donwload não está funcionando...

**Comment by browlete** [comment]
Olá, esse projeto de spoofer é meio antigo , eu upei esses arquivos em um discord , porem essa conta que os arquivos foram upados foi desativada por algum motivo, por isso não tenho mais esses arquivos , mas você pode encontrar arquivos parecido nesse fórum https://slothytech.com/how-to-bypass-fivem-ban/ , esses arquivos que tinha no meu projeto , foi retirado dai e modificados por mim, mas você pode tentar modificar você mesmo!
