### ISSUE TITLE
duvida.

### ISSUE THREAD

**Issue by enzoopr** [browlete/Fivem-Unban#5]
"system(skCrypt"
a sequencia de escape do "skCrypt" não esta sendo reconhecida, poderia me ajudar?

**Comment by browlete** [comment]
em que linha está esse erro?

**Comment by browlete** [comment]
Use o modo rrelease no compilador

**Comment by enzoopr** [comment]
main.cpp
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(104,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(105,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(106,9): warning C4129: 'P': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(106,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(107,9): warning C4129: 'M': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(107,9): warning C4129: 'W': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(107,9): warning C4129: 'C': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(107,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(108,9): warning C4129: 'S': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(108,9): warning C4129: 'D': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(108,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(109,9): warning C4129: 'M': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(109,9): warning C4129: 'W': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(109,9): warning C4129: 'T': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(109,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(110,9): warning C4129: 'A': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(110,9): warning C4129: 'L': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(110,9): warning C4129: 'T': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(110,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(111,9): warning C4129: 'h': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(112,9): warning C4129: 'c': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(113,9): warning C4129: '$': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(114,9): warning C4129: '$': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(117,9): warning C4129: 'L': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(117,9): warning C4129: 'C': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(118,9): warning C4129: 'L': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(118,9): warning C4129: 'M': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(118,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(119,9): warning C4129: 'P': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(119,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(120,9): warning C4129: 'l': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(120,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(121,9): warning C4129: 'M': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(121,9): warning C4129: 'W': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(121,9): warning C4129: '*': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(122,9): warning C4129: 'M': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(122,9): warning C4129: 'W': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(122,9): warning C4129: 'I': sequência de escape de caractere não reconhecida
C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\u202E.h(122,9): warning C4129: '*': sequência de escape de caractere não reconhecida
  Gerando código
  287 of 288 functions (99.7%) were compiled, the rest were copied from previous compilation.
    176 functions were new in current compilation
    0 functions had inline decision re-evaluated but remain unchanged
  Finalizada a geração de código
  example.vcxproj -> C:\Users\sv\Downloads\testes\2\Fivem-Unban-main\x64\Release\example.exe

**Comment by browlete** [comment]
testei aqui e está funcionando normalmente , lembre-se de compilar no modo release do visual studio

**Comment by enzoopr** [comment]
testei novamente aqui também e esta dando a mesma coisa. estou compilando ele normalmente, mais ele não esta "spoofando". se puder algum momento me ajudar meu discord é esse 'enzooq'

**Comment by browlete** [comment]
Após executar o programa você deve reiniciar o computador para que as alterações sejam salvas

**Comment by browlete** [comment]
Não dou suporte pelo discord

**Comment by enzoopr** [comment]
Da suporte por alguma outra forma?

**Comment by browlete** [comment]
não , mas segue esses passos que falei

**Comment by enzoopr** [comment]
ok, obrigado.

**Comment by browlete** [comment]
por nada
